name: hiddify
description: Cross Platform Multi Protocol Proxy Frontend.
publish_to: "none"
version: 1.1.1+10101

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  accessibility_tools: ^2.0.0
  combine: ^0.5.7-0.1.pre
  cupertino_http: ^1.5.0
  cupertino_icons: ^1.0.6
  dart_mappable: ^4.2.1
  dartx: ^1.2.0
  dio: ^5.4.1
  dio_smart_retry: ^6.0.0
  drift: ^2.16.0
  dynamic_color: ^1.7.0
  ffi: ^2.1.2
  fluentui_system_icons: ^1.1.229
  flutter_adaptive_scaffold: ^0.1.8
  flutter_animate: ^4.5.0
  flutter_displaymode: ^0.6.0
  flutter_easy_permission: ^1.1.2
  flutter_hooks: ^0.20.5
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^3.0.1
  flutter_native_splash: ^2.3.10
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^13.2.0
  grpc: ^3.2.4
  hooks_riverpod: ^2.4.10
  http: ^1.2.0
  humanizer:
    git:
      url: https://github.com/alex-relov/humanizer
      ref: up-version
  in_app_review: ^2.0.9
  intl: ^0.19.0
  json_annotation: ^4.8.1
  json_path: ^0.7.1
  launch_at_startup: ^0.2.2
  loggy: ^2.0.3
  meta: ^1.10.0
  mobile_scanner: ^4.0.0
  neat_periodic_task: ^2.0.1
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  posix: ^6.0.1
  protobuf: ^3.1.0
  protocol_handler: ^0.2.0
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.3.4
  rxdart: ^0.27.7
  sentry_dart_plugin: ^1.7.1
  sentry_flutter: ^7.16.1
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  slang: ^3.31.0
  slang_flutter: ^3.31.0
  sliver_tools: ^0.2.12
  sqlite3_flutter_libs: ^0.5.20
  timezone_to_country: ^2.1.0
  tint: ^2.0.1
  toastification: ^1.2.1
  tray_manager: ^0.2.1
  upgrader: ^9.0.0
  url_launcher: ^6.2.6
  uuid: ^4.3.3
  vclibs: ^0.1.2
  version: ^3.0.2
  watcher: ^1.1.0
  win32: ^5.5.0
  window_manager: ^0.3.8
  wolt_modal_sheet: ^0.6.0
  # permission_handler: ^11.3.0 # is not compatible with windows
  # circle_flags: ^4.0.2
  circle_flags:
    git: https://github.com/hiddify-com/flutter_circle_flags.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  riverpod_generator: ^2.3.11
  drift_dev: ^2.16.0
  ffigen: ^8.0.2
  slang_build_runner: ^3.30.0
  flutter_gen_runner: ^5.4.0
  go_router_builder: ^2.4.1
  dependency_validator: ^3.2.3
  dart_mappable_builder: ^4.2.1

dependency_overrides:
  # drift & package_info_plus are not compatible
  web: ^0.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/core/geoip.db
    - assets/core/geosite.db
    - assets/images/logo.svg
    - assets/images/tray_icon.ico
    - assets/images/tray_icon.png
    - assets/images/tray_icon_dark.ico
    - assets/images/tray_icon_dark.png
    - assets/images/tray_icon_connected.ico
    - assets/images/tray_icon_disconnected.ico
    - assets/images/connect_norouz.PNG
    - assets/images/disconnect_norouz.PNG

  fonts:
    - family: Shabnam
      fonts:
        - asset: assets/fonts/Shabnam.ttf
    - family: Emoji
      fonts:
        - asset: assets/fonts/Emoji.ttf

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/source/ic_launcher_splash.png
  android_gravity: center
  android_12:
    color: "#ffffff"
    image: assets/images/source/ic_launcher_foreground.png

ffigen:
  name: "SingboxNativeLibrary"
  description: "Bindings to Singbox"
  output: "lib/gen/singbox_generated_bindings.dart"
  headers:
    entry-points:
      - "libcore/bin/libcore.h"

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  log_level: info
  ignore_missing: true
